# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lambrie Steyn
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Lambrie Steyn
baseurl: "/"
url: "https://lambrie.github.io"
permalink: /:year/:month/:day/:title
repository: Lambrie/lambrie.github.io
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/Lambrie"
user: "Lambrie Steyn"
user_email: "lambrie45@gmail.com"
contact_url: ""
google_tracking_id: "UA-162911599-1"
google_site_verification: "UA-162911599-1"
disqus_shortname: "Lambo"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true

# Credit to MatJek for the template